language: viml
install:
    - git clone https://github.com/thinca/vim-themis
    - test/init-repos.sh
script:
    - vim --version
    - vim-themis/bin/themis
branches:
    - master
    - dev
    - temp
